import = ["/home/luis.marrero/.dotfiles/alacritty/colorsschemes/catppuccin-frappe.toml"]
live_config_reload = true

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "Ubuntu Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Ubuntu Mono Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[shell]
# program = "/bin/zsh"
program = "/usr/bin/tmux"
args = [ "new-session", "-A", "-s", "main" ]


[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_title = true
opacity = 0.95
title = "Alacritty"

[window.dimensions]
columns = 180
lines = 50

[window.padding]
x = 15
y = 5
